name: Check Markdown links

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Check relative and public links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
        with:
          args: >-
            --root-dir .
            --no-progress
            --max-retries 3
            --retry-wait-time 2
            './**/*.md'
          fail: true
          jobSummary: true
